INSERT INTO provides VALUES(1,1);
INSERT INTO provides VALUES(1,2);
INSERT INTO provides VALUES(1,3);
INSERT INTO provides VALUES(1,4);
INSERT INTO provides VALUES(1,5);
INSERT INTO provides VALUES(1,6);

INSERT INTO provides VALUES(2,1);
INSERT INTO provides VALUES(2,2);
INSERT INTO provides VALUES(2,3);
INSERT INTO provides VALUES(2,4);
INSERT INTO provides VALUES(2,5);
INSERT INTO provides VALUES(2,6);

INSERT INTO provides VALUES(3,1);
INSERT INTO provides VALUES(3,2);
INSERT INTO provides VALUES(3,3);
INSERT INTO provides VALUES(3,4);
INSERT INTO provides VALUES(3,5);
INSERT INTO provides VALUES(3,6);

INSERT INTO provides VALUES(4,1);
INSERT INTO provides VALUES(4,2);
INSERT INTO provides VALUES(4,3);
INSERT INTO provides VALUES(4,4);
INSERT INTO provides VALUES(4,5);
INSERT INTO provides VALUES(4,6);

INSERT INTO provides VALUES(5,1);
INSERT INTO provides VALUES(5,2);
INSERT INTO provides VALUES(5,3);
INSERT INTO provides VALUES(5,4);
INSERT INTO provides VALUES(5,5);
INSERT INTO provides VALUES(5,6);

INSERT INTO provides VALUES(6,1);
INSERT INTO provides VALUES(6,2);
INSERT INTO provides VALUES(6,3);
INSERT INTO provides VALUES(6,4);
INSERT INTO provides VALUES(6,5);
INSERT INTO provides VALUES(6,6);

INSERT INTO provides VALUES(7,1);
INSERT INTO provides VALUES(7,2);
INSERT INTO provides VALUES(7,3);
INSERT INTO provides VALUES(7,4);
INSERT INTO provides VALUES(7,5);
INSERT INTO provides VALUES(7,6);

INSERT INTO provides VALUES(8,1);
INSERT INTO provides VALUES(8,2);
INSERT INTO provides VALUES(8,3);
INSERT INTO provides VALUES(8,4);
INSERT INTO provides VALUES(8,5);
INSERT INTO provides VALUES(8,6);

INSERT INTO provides VALUES(9,1);
INSERT INTO provides VALUES(9,2);
INSERT INTO provides VALUES(9,3);
INSERT INTO provides VALUES(9,4);
INSERT INTO provides VALUES(9,5);
INSERT INTO provides VALUES(9,6);

INSERT INTO provides VALUES(10,1);
INSERT INTO provides VALUES(10,2);
INSERT INTO provides VALUES(10,3);
INSERT INTO provides VALUES(10,4);
INSERT INTO provides VALUES(10,5);
INSERT INTO provides VALUES(10,6);